# Generated by Django 6.0.3 on 2026-04-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер шага')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (эмодзи)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаг / Услуга',
                'verbose_name_plural': 'Шаги / Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=300, verbose_name='Адрес')),
                ('image', models.URLField(verbose_name='Фото (URL)')),
                ('pet_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во питомцев')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Тег')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('role', models.CharField(max_length=200, verbose_name='Роль')),
                ('responsibility', models.TextField(verbose_name='Обязанности')),
                ('image', models.URLField(verbose_name='Фото (URL)')),
                ('color', models.CharField(default='#4AADA1', max_length=7, verbose_name='Цвет акцента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=200, verbose_name='Порода')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('other', 'Другое')], default='dog', max_length=10, verbose_name='Вид')),
                ('gender', models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], default='male', max_length=10, verbose_name='Пол')),
                ('image', models.URLField(verbose_name='Фото (URL)')),
                ('video', models.URLField(blank=True, verbose_name='Видео (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_adopted', models.BooleanField(default=False, verbose_name='Усыновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='shelters.shelter', verbose_name='Приют')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-created_at'],
            },
        ),
    ]
