# Generated by Django 4.2.29 on 2026-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название приюта')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('description', models.TextField(verbose_name='Расскажите о приюте')),
            ],
        ),
    ]
