# Generated by Django 4.2.29 on 2026-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='type',
            field=models.CharField(choices=[('private', 'Частный'), ('state', 'Государственный')], default='private', max_length=20, verbose_name='Тип приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
