# Generated by Django 4.2.29 on 2026-04-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('species', models.CharField(max_length=50, verbose_name='Вид (кот/собака)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Фото')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='shelters.shelter', verbose_name='Приют')),
            ],
        ),
    ]
