# Generated by Django 4.2.29 on 2026-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Самец'), ('female', 'Самка')], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('hamster', 'Хомяк'), ('rabbit', 'Кролик')], max_length=20, verbose_name='Вид'),
        ),
    ]
