# Generated by Django 6.0.3 on 2026-04-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_pet_age_pet_breed_pet_description_pet_gender_and_more'),
        ('shelters', '0003_remove_shelter_address_remove_shelter_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_pets', to='shelters.shelter', verbose_name='Приют'),
        ),
    ]
